#!/bin/sh

case "$1" in
remove)
    echo "Package is being removed"
    if systemctl is-enabled --quiet border0.service; then systemctl disable border0.service; fi
    if systemctl is-active --quiet border0.service; then systemctl stop border0.service; fi
    if [ -f /etc/systemd/system/border0.service ]; then rm /etc/systemd/system/border0.service; fi

    systemctl daemon-reload

    if [ -f /usr/local/bin/border0 ]; then rm /usr/local/bin/border0; fi
    if [ -L /usr/local/bin/border0 ]; then rm /usr/local/bin/border0; fi
    if [ -f /usr/bin/border0 ]; then rm /usr/bin/border0; fi

    echo "We are leaving the /etc/border0 config file in place"
    ;;
purge)
    echo "Package is being purged"
    if systemctl is-enabled --quiet border0.service; then systemctl disable border0.service; fi
    if systemctl is-active --quiet border0.service; then systemctl stop border0.service; fi
    if [ -f /etc/systemd/system/border0.service ]; then rm /etc/systemd/system/border0.service; fi

    systemctl daemon-reload

    if [ -f /usr/local/bin/border0 ]; then rm /usr/local/bin/border0; fi
    if [ -L /usr/local/bin/border0 ]; then rm /usr/local/bin/border0; fi
    if [ -f /usr/bin/border0 ]; then rm /usr/bin/border0; fi
    if [ -d /etc/border0 ]; then rm -rf /etc/border0; fi
    ;;

upgrade)
    # This is an upgrade
    # $2 contains the version being upgraded from
    # we will handle this separately in the binary, for now this is an NO-OP
    ;;
*)
    echo "Unknown argument: $1"
    ;;
esac
