#!/bin/bash

function create_config_file {
  echo "Creating config file..."
  echo """
token: ${BORDER0_CONNECTOR_TOKEN}
""" >/etc/border0/border0.yaml
}
function check_and_replace {
  if [ -f /usr/local/bin/border0 ]; then
    echo "Replacing /usr/local/bin/border0 with symlink to /usr/bin/border0"
    rm /usr/local/bin/border0
    ln -s /usr/bin/border0 /usr/local/bin/border0
  fi
}

case "$1" in
configure)
  check_and_replace
  if [ "$DEBIAN_FRONTEND" = "noninteractive" ]; then
    echo "Running in non-interactive mode."
    if [ -n "$BORDER0_CONNECTOR_TOKEN" ]; then
      border0 connector install --v2 --daemon-only
      create_config_file
    else
      echo -e "BORDER0_CONNECTOR_TOKEN is not set.\nPlease run the install manually... \n'border0 connector install --v2'"
    fi
  elif [ -n "$BORDER0_CONNECTOR_TOKEN" ]; then
    border0 connector install --v2 --daemon-only
    create_config_file
  else
    if [ -f /etc/systemd/system/border0.service ]; then
      echo "Looks like border0.service is already installed."
      exit 0
    fi
    echo "Running Border0 Connector Install."
    attempts=3
    while [ $attempts -gt 0 ]; do
      read -p "Do you want to proceed? (y/n) " choice
      case "$choice" in
      y | Y)
        echo "Running 'border0 connector install --v2'"
        border0 connector install --v2
        break
        ;;
      n | N)
        echo "You can always execute 'border0 connector install --v2' to install the connector later."
        break
        ;;
      *)
        echo -e "Invalid choice. \nYou can always execute 'border0 connector install --v2' to install the connector later."
        let "attempts--"
        if [ $attempts -eq 0 ]; then
          echo "Exceeded maximum number of attempts."
          break
        fi
        continue
        ;;
      esac
    done
  fi

  ;;
upgrade)
  echo "Upgrading Border0 Connector..."
  if systemctl is-active --quiet border0.service; then
    echo "Restarting border0.service..."
    systemctl restart border0.service
  fi
  ;;
*)
  echo "Unknown argument: $1"
  ;;
esac
