#!/bin/bash
# postinst

# create a config file function
function create_config_file {
  echo "Creating config file..."
  # create config file
  echo """
token: ${BORDER0_CONNECTOR_TOKEN}
""" >/etc/border0/border0.yaml
}

case "$1" in
configure)
  # This is a fresh installation or a reconfiguration
  # Check if we are running in a non-interactive environment
  if [ "$DEBIAN_FRONTEND" = "noninteractive" ]; then
    # Non-interactive behavior here
    echo "Running in non-interactive mode."
    if [ -n "$BORDER0_CONNECTOR_TOKEN" ]; then
      # if token is set, run automated install in noninteractive mode
      border0 connector install --v2 --daemon-only
      create_config_file
    else
      echo -e "BORDER0_CONNECTOR_TOKEN is not set.\nPlease run the install manually... \n'border0 connector install --v2'"
    fi
  elif [ -n "$BORDER0_CONNECTOR_TOKEN" ]; then
    # if token is set, run automated install in interactive mode
    border0 connector install --v2 --daemon-only
    create_config_file
  else
    # check if border0.service is already installed and exit if it is
    if [ -f /etc/systemd/system/border0.service ]; then
      echo "Looks like border0.service is already installed."
      exit 0
    fi
    echo "Running Border0 Connector Install."
    # Interactive behavior
    attempts=3
    while [ $attempts -gt 0 ]; do
      read -p "Do you want to proceed? (y/n) " choice
      case "$choice" in
      y | Y)
        echo "Running 'border0 connector install --v2'"
        border0 connector install --v2
        break
        ;;
      n | N)
        echo "You can always execute 'border0 connector install --v2' to install the connector later."
        break
        ;;
      *)
        echo -e "Invalid choice. \nYou can always execute 'border0 connector install --v2' to install the connector later."
        let "attempts--"
        if [ $attempts -eq 0 ]; then
          echo "Exceeded maximum number of attempts."
          break
        fi
        continue
        ;;
      esac
    done
  fi

  ;;
upgrade)
  # This is an upgrade
  # $2 contains the version being upgraded from
  # we will handle this separately in the binary
  # For now this is an NO-OP
  ;;
*)
  echo "Unknown argument: $1"
  ;;
esac
