#!/bin/bash

function create_config_file {
  echo "Creating config file..."
  echo """
token: ${BORDER0_TOKEN}
""" >/etc/border0/border0.yaml
}

case "$1" in
configure)
  if [ -n "$2" ]; then
    echo "Upgrading Border0 Connector from version $2"
    if systemctl is-active --quiet border0.service; then
      echo "Restarting border0.service..."
      systemctl restart border0.service
    else
      echo -e "Looks like border0.service is not running.\nyou can check the status with 'systemctl status border0.service'\nIt can be started with 'systemctl start border0.service'"
    fi
  else
    echo "New installation."
    if [ "$DEBIAN_FRONTEND" = "noninteractive" ]; then
      echo "Running in non-interactive mode."
      if [ -n "$BORDER0_TOKEN" ]; then
        border0 connector install --daemon-only
        create_config_file
      else
        echo -e "BORDER0_TOKEN is not set.\nPlease run the install manually... \n'border0 connector install'"
      fi
    elif [ -n "$BORDER0_TOKEN" ]; then
      border0 connector install --daemon-only
      create_config_file
    else
      echo "Running Border0 Connector Install."
      attempts=2
      while [ $attempts -gt 0 ]; do
        read -p "Do you want to proceed? (y/n) " choice
        case "$choice" in
        y | Y)
          echo "Running 'border0 connector install'"
          border0 connector install
          break
          ;;
        n | N)
          echo "You can always execute 'border0 connector install' to install the connector later."
          break
          ;;
        *)
          echo -e "Invalid choice. \nYou can always execute 'border0 connector install' to install the connector later."
          let "attempts--"
          if [ $attempts -eq 0 ]; then
            echo "Exceeded maximum number of attempts."
            break
          fi
          continue
          ;;
        esac
      done
    fi
  fi
  ;;
*)
  echo "Unknown argument: $1"
  ;;
esac
