name: Docker image build n publish

on:
  workflow_dispatch:
  push:
    # branches: [ main ]
    # paths:
    #   - client/**
    #   - cmd/**
    #   - internal/**

permissions:
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx create --use
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm \
          -t ghcr.io/${{ github.actor }}/connector:latest \
          -t ghcr.io/${{ github.actor }}/connector:${{ github.ref_name }} \
          -t ghcr.io/${{ github.actor }}/cli:latest \
          -t ghcr.io/${{ github.actor }}/cli:${{ github.ref_name }} \
          -t ghcr.io/${{ github.actor }}/border0:latest \
          -t ghcr.io/${{ github.actor }}/border0:${{ github.ref_name }} \
          --push .
          docker buildx ls


      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.actor }}/border0:latest
      #       ghcr.io/${{ github.actor }}/border0:${{ github.ref_name }}

