name: Docker image build n publish

on:
  workflow_dispatch:
  push:
    # branches: [ main ]
    # paths:
    #   - client/**
    #   - cmd/**
    #   - internal/**

permissions:
  id-token: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/border0:latest
            ghcr.io/${{ github.actor }}/border0:${{ github.ref_name }}

